name: Build e Testes Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Forçar uso do Java 21 em todo o workflow
        run: |
          echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV

      - name: Instalar Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Compilar projeto
        run: mvn -B package --file Sprint-RestAPI/pom.xml

      - name: Iniciar aplicação Spring Boot
        run: mvn spring-boot:run --file Sprint-RestAPI/pom.xml &
      
      - name: Aguardar servidor iniciar
        run: |
          echo "Aguardando servidor subir..."
          sleep 15

      - name: Executar testes
        run: mvn test --file Sprint-RestAPI/pom.xml

      - name: Publicar Relatórios de Testes
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-testes
          path: Sprint-RestAPI/target/surefire-reports
