name: Build e Testes Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Instalar Google Chrome (Necessário para Selenium)
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Compilar e Empacotar
        run: mvn clean package -DskipTests --file Sprint-RestAPI/pom.xml

      - name: Iniciar Aplicação e Rodar Testes de UI
        run: |
          mvn spring-boot:run --file Sprint-RestAPI/pom.xml &
          echo "Aguardando inicialização do Spring Boot..."
          sleep 20
          mvn test --file Sprint-RestAPI/pom.xml
        env:
          CHROME_HEADLESS: true 

      - name: Upload de Artefatos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: relatorios-execucao
          path: Sprint-RestAPI/target/surefire-reports/