name: Pipeline Sprint RestAPI

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    env:
      SPRING_DATASOURCE_URL: ${{ secrets.DB_URL }}
      SPRING_DATASOURCE_USERNAME: ${{ secrets.DB_USERNAME }}
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.DB_PASSWORD }}
      CHROME_HEADLESS: ${{ vars.CHROME_HEADLESS }}

    steps:
       name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Instalar Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Build do Projeto
        run: mvn clean package -DskipTests --file Sprint-RestAPI/pom.xml

      - name: Iniciar Aplicação e Testes
        run: |
          mvn spring-boot:run --file Sprint-RestAPI/pom.xml &
          echo "Aguardando 20 segundos para a API subir..."
          sleep 20
          mvn test --file Sprint-RestAPI/pom.xml

      - name: Gerar Resumo
        if: always()
        run: |
          echo "### Relatório de Automação" >> $GITHUB_STEP_SUMMARY
          echo "| Status do Build | Testes Executados |" >> $GITHUB_STEP_SUMMARY
          echo "| :--- | :--- |" >> $GITHUB_STEP_SUMMARY
          echo "|  Concluído | Sim |" >> $GITHUB_STEP_SUMMARY