- name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Executar análise estática com Maven
        run: mvn verify -DskipTests --file Sprint-RestAPI/pom.xml 

      - name: Publicar relatórios
        uses: actions/upload-artifact@v4
        with:
          name: analise-estatica
          path: |
            Sprint-RestAPI/target/checkstyle-result.xml
            Sprint-RestAPI/target/spotbugsXml.xml